### ISSUE TITLE
Bar plot per million

### ISSUE THREAD

**Issue by birdsarah** [jwrichar/COVID19-mortality#4]
I really like the bar visualization, found a per million version helpful / interesting too:

https://github.com/birdsarah/COVID19-mortality/blob/counts_per_million/State-wise%20Unreported%20COVID-19%20Cases%20in%20the%20U.S..ipynb

![image](https://user-images.githubusercontent.com/1796208/77197765-bbc28880-6ab3-11ea-88ad-a8f680522213.png)

**Comment by jwrichar** [comment]
Yeah, that's much more interesting than the current bar viz!  I like that LA pops out, because I've noticed that their numbers were consistently much higher than I'd expect (large outbreak in New Orleans?).

Would you mind opening up a PR with the new viz in the [covid-dashboard](https://github.com/jwrichar/covid19-dashboard) repo?  That way we can do a PR into the live dashboard repo to start publishing this plot to the live site.

**Comment by birdsarah** [comment]
> Would you mind opening up a PR with the new viz in the covid-dashboard repo? That way we can do a PR into the live dashboard repo to start publishing this plot to the live site.

Sure

**Comment by jwrichar** [comment]
The new viz is now live on the main dashboard!
https://covid19dashboards.com/covid-19-us-case-estimation/

**Comment by birdsarah** [comment]
Very nice. Apologies for not following through on the PR, I've been covid detoxing. I was getting a little overwhelmed.

**Comment by jwrichar** [comment]
I understand 100%
